#!/usr/bin/env python3
"""Generate research/CATALOG.md from experiments/*/result.json."""
import argparse
import json
from pathlib import Path

ORDER = ["accepted", "inconclusive", "rejected", "broken", "pending"]


def _title(path):
    if path.exists():
        for line in path.read_text().splitlines():
            if line.startswith("# "):
                return line[2:].strip()
    return ""


def _first_line_under(path, heading):
    if not path.exists():
        return ""
    capturing = False
    for line in path.read_text().splitlines():
        if line.startswith("## "):
            capturing = line[3:].strip().lower() == heading.lower()
        elif capturing and line.strip():
            return line.strip()
    return ""


def _elo(sprt):
    if not sprt or sprt.get("elo") is None:
        return "n/a"
    if sprt.get("elo_err") is None:
        return f"{sprt['elo']:+.1f}"
    return f"{sprt['elo']:+.1f} ± {sprt['elo_err']:.1f}"


def _cell(text):
    return str(text).replace("|", "\\|")


def _load(exp):
    path = exp / "result.json"
    result = json.loads(path.read_text()) if path.exists() else {}
    sprt = result.get("sprt") or {}
    return {
        "id": exp.name,
        "status": result.get("status", "pending"),
        "title": _title(exp / "hypothesis.md"),
        "elo": _elo(sprt),
        "games": sprt.get("games", 0),
        "baseline": (result.get("baseline_commit") or "")[:12],
        "note": result.get("reason") or _first_line_under(exp / "trace.md", "Summary"),
    }


def render(root):
    rows = [_load(p) for p in sorted((root / "experiments").iterdir()) if p.is_dir()]
    out = [
        "# Experiment catalog",
        "",
        "Generated by `research/scripts/catalog.sh`. Do not edit.",
        "",
    ]
    for status in ORDER:
        group = [r for r in rows if r["status"] == status]
        if not group:
            continue
        out += [
            f"## {status.capitalize()} ({len(group)})",
            "",
            "| id | hypothesis | Elo | games | baseline | note |",
            "|---|---|---|---|---|---|",
        ]
        for r in group:
            cells = [r["id"], r["title"], r["elo"], r["games"], r["baseline"], r["note"]]
            out.append("| " + " | ".join(_cell(c) for c in cells) + " |")
        out.append("")
    out += ["## Proofs", "", "No Lean proofs yet.", ""]
    return "\n".join(out)


def main(argv=None):
    p = argparse.ArgumentParser()
    p.add_argument("--root", default=str(Path(__file__).resolve().parent.parent))
    root = Path(p.parse_args(argv).root)
    (root / "CATALOG.md").write_text(render(root))


if __name__ == "__main__":
    main()
